import Navbar from '../components/Navbar.jsx'
import Head from 'next/head'
import Main from '../components/Main.jsx'
import Image from 'next/image'
import About from '../components/About.jsx'
import Skills from '../components/Skills.jsx'
import Projects from '../components/Projects.jsx'
import Contact from '../components/Contact.jsx'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Ash | Software Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar /> 
      <Main />
      <About />
      <Skills />
      {/* <Projects /> */}
      <Contact />
    </div>
  )
}
