'use client'
import { useRef, useEffect } from 'react';
import Head from 'next/head'
import Main from '../components/Main.jsx'
import About from '../components/About.jsx'
import Projects from '../components/Projects.jsx'
import Footer from '@/components/Footer.jsx'
import Contact from '@/components/Contact.jsx'
import BackgroundParticles from '@/components/ui/backgroundParticles.jsx'
import NavMenu from '@/components/NavMenu.jsx'
import Lenis from 'lenis';

export default function Home() {
  // useEffect(() => {
  //   const lenis = new Lenis()
  //   function raf(time) {
  //     lenis.raf(time)
  //     requestAnimationFrame(raf)
  //   }
  //   requestAnimationFrame(raf)
  // })

  return (
    // <div className="min-h-screen w-full overflow-y-auto scroll-smooth">
    <div className="min-h-screen w-full font-trirong">
      <Head>
        <title>Ash | Software Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BackgroundParticles />
      <NavMenu />
      <Main />
      <About />
      <Projects />
      <Contact />
      {/* <Footer /> */}
    </div>

  )
}